title: Getting started with micro:bit
hero_image: images/banner.png
description: Getting started with the micro:bit
version: 1
listed: true
copyedit: false
last_tested: "2023-10-03"
steps:
  - title: Introduction
  - title: Meet the micro:bit
  - title: The MakeCode editor
  - title: Connect the micro:bit
  - title: Using the LEDs
  - title: How to use the sensors
  - title: Inputs
  - title: Sounds
  - title: Powering the micro:bit
  - title: How to share your code
  - title: What next?
